name: lector_huella
description: "Lector de huella"
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.3.0
  local_auth_android: ^1.0.12
  libsql_dart: ^0.4.6
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
